### ISSUE TITLE
Add WithMessagef and WrapStackf to be consistent with Wrapf.

### ISSUE THREAD

**Issue by jeffreydwalter** [pkg/errors#141]
Any chance of getting a WithMessagef and a WrapStackf method to go along with Wrapf? Seems inconsistent to not have them.

**Comment by davecheney** [comment]
I was sure there was another issue for this but I cannot find it.

The TL;DR is i'm wary of adding more methods to this package as effectively they can never be removed. My proposal is to audit all the uses of this package (found on godoc) and determine the frequency that people use `fmt.Sprintf` + `WithMessage` and/or `WithStack` to determine how often this pattern occurs. If it is frequent that would justify adding a formatting version of `WithMessage`, `WithStack`

**Comment by jeffreydwalter** [comment]
I can tell you for sure that I am using that functionality.

**Comment by decibel** [comment]
Perhaps a better alternative would be making all the functions operate as formatters and just short-cutting in the case of `len(args) == 0`. That wouldn't provide the exact behavior that fmt.Sprintf does, but I think it's a reasonable tradeoff.

**Comment by jeffreydwalter** [comment]
I think that's a great idea. :)

**Comment by puellanivis** [comment]
Altering the behavior in this way would be a recipe for making the behavior of these functions unpredictable and unexpected. This will inevitably result in misuse, bugs, and people being surprised by the functionality provided.

Widely used libraries need to avoid surprising developers with unexpected behaviors. They are eternally and always a threat to reliable programming.

**Comment by decibel** [comment]
@davecheney I submit that such an audit should also look for string concatenation, since in this context that's just an alternative form of fmt.Sprtinf.

**Comment by puellanivis** [comment]
Because fmt.Print() and fmt.Sprintf() have very different behavior. If they are a formatter, they should be named `XXXf`, otherwise they should not be a formatter. Mixing the behavior of “formatter if XY, otherwise not” would be a bad idea.

Note that `fmt.Sprintf("%s")` returns something very different from `fmt.Sprint("%s")`. Mixing that behavior is asking for people to misunderstand the rules about when it will act like which.

**Comment by decibel** [comment]
Wrap()/Wrapf() already breaks that notion (though, I think there's a case to be made for making Wrap() wore the same as Sprint()). The proposal is to make WithMessage symmetric with Wrap/Wrapf. From an API perspective I think it's a lot more confusing that there's a Wrapf() but no WithMessagef().

(I'm assuming that the proposal for WithStackf() is a think-o, since obviously there's no point to doing that.)

**Comment by puellanivis** [comment]
The Wrap/Wrapf “break” from the Sprint/Sprintf is in that Wrap only permits one argument. Not that there is a single function that provides both behaviors.

That Wrap does not exactly match the signature of an Sprint call is irrelevant to the matter of if a single function should provide both behaviors depending upon the number of arguments.

**Comment by davecheney** [comment]
Closed #118
