### ISSUE TITLE
PROPOSAL: Add Message() method to withMessage{}

### ISSUE THREAD

**Issue by decibel** [pkg/errors#147]
When dealing with multiple layers of errors wrapped by WithMessage(), there's no good way to obtain each individual message.

**Comment by davecheney** [comment]
Sorry, this is by design. The errors package gives you a way to add textual annotations to your error that can be Fprinted, and a way to remove all of that guff and recover the original error. 

I suggest following the way os.PathError works, a named type that can be asserted, which contains a named field with subsequent errors.
