### ISSUE TITLE
Proposal: verbose errors

### ISSUE THREAD

**Issue by RaduBerinde** [pkg/errors#59]
In many cases when we're generating an error we know that the particular error, if it happens, is indicative of a bug. In those cases, it's very useful if the error message contains more information (like file:line). 

Errors might be handled at a different layer (e.g. sent out to a client using `%s`) where the original context of the error is lost.

The proposal is to add a version of `Errorf` which results in a "verbose" error which automatically includes the file:line where it was generated as part of the error message.

**Comment by davecheney** [comment]
Hello,

Thank you for raising this issue. I believe with version 0.7.0 this is already supported via the `%+v` formatting verb.

**Comment by RaduBerinde** [comment]
Hi Dave,
The layer that is formatting the error in general doesn't know the context of the error anymore - it doesn't know which errors it should format using `%+v` and which using `%s`.
The key part of the proposal is having the error itself internally keep track of this "verbosity" indicator.

**Comment by davecheney** [comment]
I'm not sure know how to satisfy this request, once an error value is turned into a string, obviously any other information is lost. 

Are you suggesting a new helper, something like `errors.ErrorfWithStacktrace` that will force the file:line information into the .Error() string output when printed ?

**Comment by davecheney** [comment]
If this is what you are asking for I can see two possibilities:

1. A new pair (quad) of top level functions, ie, we'd have `New` and `NewWithFileAndLine`, and so on.
2. A wrapper function, `errors.WithFileAndLine` (terrible name) that would "convert" an errors's `.Error()` format from just returning the message to returning something like `file:line: message`

Neither of these is particularly appealing.

**Comment by davecheney** [comment]
Oh, im.sorry I think understand what you mean, you want

     errors.Errorf("...", arg)

Where the elided part is some formatting verb that adds the file and line
of the call to Errorf.

Is that correct?

**Comment by RaduBerinde** [comment]
I was suggestion a new helper (e.g. `errors.Verbosef` or whatever). It can also be a verb to `errors.Errorf`.

**Comment by davecheney** [comment]
Thanks for your reply. I can think of three ways to do this, none of them
are without (serious) drawbacks.

The first would be something like

errors.Error("%+v", arg).Error()

To say we want the "verbose" output when Error is called. This is
problematic because there is an ambiguity over does the %+v get applied to
the argument arg, or consumed to signal Error() should modify its
behaviour. Maybe this is solvable with documentation, but it still leaves
New and Wrap. Where could we put the flag to modify their return value's
.Error() method?

I don't think this is a good solution.

Adding new methods like errors.Verbosef solves that first problem, but
you'd have to do it for all four of New, Errorf, Wrap, and Wrapf. I'm sorry
but four additional helpers is not something I'm prepared to do.

Adding some kind of modified function like

   func Verbose(err error) error

Which took an error and returned an error with the "verbose details" bit
set is a possibility. But both this and the previous method suffer from the
issue that if the original called did not use the verbose form, or wrapper,
then when you pass that error to fmt.Printf, the chance to turn on the
verbose bit is long gone and not in code you control.

This leaves printing this error. Ideally we would have three verbs
available, %s, %v and %+v which would print the message, a slightly more
verbose version (such as you suggested) and the full stack trace of the
error as it does in 0.7.0.

Unfortunately in my research %s and %v are used interchangeably (as they
have the same behavior with the srdlib's built in errors package) with a
strong preference to using %v more often than %s.

There are two practical solutions in can see. The first is to add something
like errors.Verbose which takes an error and returns an error with the
message modified. This feels like a minefield of bikes shedding about the
exact format of the information added (file and line, what about the
function name? What about the package name? etc)

The second choice would be to try to reclaim %v and have it print the file
and line. Leaving %s for printing just the message, and %+v for the full
stack trace.

The second is my preferred option as it leaves the control in the code
doing the printing, not the code that generated the error.

**Comment by tamird** [comment]
@davecheney I believe the specific desire here is indeed for the code that generates the error to be able to indicate that the error needs to be verbose. In particular we often generate errors in CockroachDB that are indicative of bugs - those comments are not for end-user consumption, and so we know we always want them to print with higher verbosity, regardless of the code that prints them.

`.Verbose()` seems like the most practical option to me.

**Comment by davecheney** [comment]
I'm concerned that will lead to copy pasta

err := errors.New("oops")
err = errors.Verbose(err) //because reasons

**Comment by davecheney** [comment]
Tamir, with reference to your point about your usage in cockroachdb, can
you tell me if the %+v feature added in 0.7.0 is useful. And if not, How
could it be changed.

If you could give this feedback on a _new_ issue that would be strongly
preferred.

Thanks

**Comment by RaduBerinde** [comment]
Tamir and I are referring to the exact same issue. We want to control the verbosity *at the point where the error is generated*, not at the point where we are printing the error.

The proposed `Verbose` works though I agree `errors.Verobse(error.Errorf(..))` is a little clunky.. We could provide a helper just for this one `Verbosef` but not for the other three (`Verbose` can still be used specifically if needed).

**Comment by RaduBerinde** [comment]
Here is a high level illustration of why this is useful. Say our program logic is something like this:

```
1:  for {
2:    receive user request
3:    call into module X to satisfy request
4:      -> module X calls into module Y
5:         ..
6:            -> somewhere deep in the bowels of a submodule, an error is generated and bubbles up
7:
8:    send error to user
9:  }
```

Some errors are expected to be seen by a user (e.g. "no more space"); other errors are caused by some internal inconsistency and indicate a bug. We want the latter to print more verbosely. We know the difference *when we generate the error* (line 6) but the "send error to client" code in line 8 does not know - all it has is the `error`. So the "verbosity" needs to be stored inside the error.

**Comment by davecheney** [comment]
@RaduBerinde thank you for your explanation. In your example it does not look like there are any calls to fmt.Sprintf or anything that would convert the error value into a string. That is, the original error arrives at the top of the call stack, possibly wrapped, but otherwise intact.

Is that correct ?

**Comment by davecheney** [comment]
I saw you edit your original comment. That's hard to keep track of, could you please answer any followup questions in a new comment. Thanks.

**Comment by RaduBerinde** [comment]
I had edited it immediately after writing it to make it more clear (way before your followup question)..

**Comment by davecheney** [comment]
Thanks for confirming. Could you please respond to my question in https://github.com/pkg/errors/issues/59#issuecomment-228231951

**Comment by RaduBerinde** [comment]
The conversion to string would happen in step 8 "send error message to user".

**Comment by davecheney** [comment]
Thank you for confirming. Why won't `%+v` work for you then. Is the problem that given an arbitrary error value, you cannot decide if it's important enough to give the user all the information, or just some of it ?

**Comment by RaduBerinde** [comment]
Exactly. Like I said above: 
> Some errors are expected to be seen by a user (e.g. "no more space"); other errors are caused by some internal inconsistency and indicate a bug. We want the latter to print more verbosely

**Comment by davecheney** [comment]
Real talk, what you're asking for is going to make the surface area of this package larger and certainly more complex to use. This is in conflict with the goal of this package to be a proof of concept for improving the errors package in the standard library in Go 1.8.

If you have a certain class of errors that you know are more serious, or verbose, then you can define your own error type that adds any detail you want. Even something as simple as this
```go
_, file, line, _ := runtime.Callers(1)
return errors.Errorf("%s:%d: %s", file, line, "critical error happened here")
```
Should give you what you want. 

Can I ask why you do not want to always use `%+v` when printing the error back to the user. What about it is not acceptable? Is there a way we can define an intermediate format, somewhere between printing just the error's message with `%s`, and the full stack dump that `%+v`.

**Comment by RaduBerinde** [comment]
It's your call, but I don't see how it makes the package more complex to use. Anybody who doesn't care about this would continue using it just like today. It does make the exposed interface more complex (in that it has a couple more functions), sure.

> Can I ask why you do not want to always use %+v when printing the error back to the user. What about it is not acceptable?

Because the messages for "normal" errors would be less user-friendly and harder for the user to understand. In our case these are errors returned in a SQL session so it's not really feasible to dump a lot of obscure information. It only makes sense for errors that weren't intended to be ever seen by a user.

**Comment by davecheney** [comment]
> It does make the exposed interface more complex (in that it has a couple more functions), sure.

The type returned from `error.{New,Wrap,Errorf,Wrapf}` has to be `error` otherwise this breaks
```go
err := fn() // something that returns a type from this errors package
if err != nil {
       return err
}
err = fn2() // something that returns an error generated from fmt.Errorf
```
This has come up a few times in other issues on this repo, the short version is the type return from this packages' methods must be `error`, not something like `errors.Error`.

> Because the messages for "normal" errors would be less user-friendly and harder for the user to understand. In our case these are errors returned in a SQL session so it's not really feasible to dump a lot of obscure information. It only makes sense for errors that weren't intended to be ever seen by a user.

ok, I can see that you don't want to always return a multiline stacktrace, but would you be ok with always returning to the caller say

     driver.go:9999: out of space

**Comment by RaduBerinde** [comment]
The solution you proposed (`func Verbose(err error) error`) doesn't need to do that - it would be very close to how `Wrap` works. In fact, it could even use `Wrap` and use the file:line as the extra message.

> ok, I can see that you don't want to always return a multiline stacktrace, but would you be ok with always returning to the caller say [..]

No - we want the "normal" errors to not have any filenames and line numbers in them; one big reason is that we don't want the error messages to vary depending on the build..

**Comment by RaduBerinde** [comment]
Of course - I do understand the hesitation to add random stuff to the package, so feel free to close this.

A generalization of this concept to maybe consider in the future is allowing "tagging" of errors with arbitrary information (e.g. setting key/values with `string` keys and `interface{}` values). In my experience this functionality can be very useful - similar to how `Wrap` adds a message to the error, an intermediate layer can set an ID or a flag, and that could be used in an upper layer to make a decision when handling the error.

**Comment by davecheney** [comment]
@RaduBerinde as to your last point, please see #34, which is regrettably, closed.

**Comment by davecheney** [comment]
> The solution you proposed (func Verbose(err error) error) doesn't need to do that - it would be very close to how Wrap works. In fact, it could even use Wrap and use the file:line as the extra message.

I don't think I understand. Can you please explain in more detail how this would work.

**Comment by RaduBerinde** [comment]
E.g.:
```
func Verbose(err error) error {
  _, file, line, _ := runtime.Caller(1)
  return errors.Wrap(err, fmt.Sprintf("%s:%d", file, line))
}
```

**Comment by davecheney** [comment]
I'm sorry but I do not plan to add this helper. I understand your use case but am not sure that it common enough to increase the surface area of this package. I'm almost certain that this helper would not make the cut if this package was accepted (in part or in piece) into the standard library so I recommend that you write this helper in you own codebase.
